"""Lightweight ontology helpers used by deterministic pipeline stages."""

from medical_kg_nlp.ontology.phase1 import (
    PHASE1_ALLOWED_ASSERTIONS,
    PHASE1_ALLOWED_TYPES,
    PHASE1_ASSERTABLE_TYPES,
    PHASE1_CODABLE_TYPES,
    PHASE1_ENTITY_TYPE_RULES,
    PHASE1_INTERNAL_RELATION_RULES,
    PHASE1_REQUIRED_KEYS,
    PHASE1_SECTION_RULES,
    PHASE1_TYPE_BY_ENTITY_TYPE,
    PHASE1_TYPE_PRIORITY,
    OntologyRuleResult,
    Phase1EntityTypeRule,
    Phase1InternalRelationRule,
    Phase1SectionRule,
    assertions_allowed,
    candidates_allowed,
    expected_code_system,
    internal_relation_allowed,
    resolve_overlap,
    section_rule_for_heading,
)

__all__ = [
    "OntologyRuleResult",
    "PHASE1_ALLOWED_ASSERTIONS",
    "PHASE1_ALLOWED_TYPES",
    "PHASE1_ASSERTABLE_TYPES",
    "PHASE1_CODABLE_TYPES",
    "PHASE1_ENTITY_TYPE_RULES",
    "PHASE1_INTERNAL_RELATION_RULES",
    "PHASE1_REQUIRED_KEYS",
    "PHASE1_SECTION_RULES",
    "PHASE1_TYPE_BY_ENTITY_TYPE",
    "PHASE1_TYPE_PRIORITY",
    "Phase1EntityTypeRule",
    "Phase1InternalRelationRule",
    "Phase1SectionRule",
    "assertions_allowed",
    "candidates_allowed",
    "expected_code_system",
    "internal_relation_allowed",
    "resolve_overlap",
    "section_rule_for_heading",
]
