"""Reusable acquisition, curation, and dataset-snapshot primitives."""

from medical_kg_nlp.mining.catalog import DuckDBMiningCatalog, ParquetSnapshotWriter
from medical_kg_nlp.mining.ports import (
    ArtifactStorePort,
    CoveragePlannerPort,
    DeduplicatorPort,
    DocumentParserPort,
    ProposalLabelerPort,
    QualityGatePort,
    ReviewBackendPort,
    SourceConnectorPort,
)
from medical_kg_nlp.mining.records import (
    AccessClass,
    AnnotationLayer,
    AnnotationProposal,
    ConceptLink,
    CoverageCell,
    CoverageReport,
    DatasetSnapshot,
    DiscoveredArtifact,
    MinedDocument,
    RedistributionPolicy,
    RelationProposal,
    ReviewStatus,
    SourceArtifact,
    SourceRequest,
    StoredObject,
)
from medical_kg_nlp.mining.storage import FsspecArtifactStore, LocalArtifactStore

__all__ = [
    "AccessClass",
    "AnnotationLayer",
    "AnnotationProposal",
    "ArtifactStorePort",
    "ConceptLink",
    "CoverageCell",
    "CoveragePlannerPort",
    "CoverageReport",
    "DatasetSnapshot",
    "DeduplicatorPort",
    "DiscoveredArtifact",
    "DocumentParserPort",
    "DuckDBMiningCatalog",
    "FsspecArtifactStore",
    "LocalArtifactStore",
    "MinedDocument",
    "ParquetSnapshotWriter",
    "ProposalLabelerPort",
    "QualityGatePort",
    "RedistributionPolicy",
    "RelationProposal",
    "ReviewBackendPort",
    "ReviewStatus",
    "SourceArtifact",
    "SourceConnectorPort",
    "SourceRequest",
    "StoredObject",
]
