"""Reusable acquisition, curation, and dataset-snapshot primitives."""

from medical_kg_nlp.mining.catalog import DuckDBMiningCatalog, ParquetSnapshotWriter
from medical_kg_nlp.mining.ports import (
    ArtifactStorePort,
    CoveragePlannerPort,
    DeduplicatorPort,
    DocumentParserPort,
    ProposalLabelerPort,
    QualityGatePort,
    ReviewBackendPort,
    SourceConnectorPort,
)
from medical_kg_nlp.mining.policy import MiningQualityGate, PolicyDecision, SourcePolicyGate
from medical_kg_nlp.mining.records import (
    AccessClass,
    AnnotationLayer,
    AnnotationProposal,
    ConceptLink,
    CoverageCell,
    CoverageReport,
    DatasetSnapshot,
    DiscoveredArtifact,
    MinedDocument,
    RedistributionPolicy,
    RelationProposal,
    ReviewStatus,
    SourceArtifact,
    SourceRequest,
    StoredObject,
)
from medical_kg_nlp.mining.storage import FsspecArtifactStore, LocalArtifactStore
from medical_kg_nlp.mining.registry import (
    LicenseMode,
    RetentionPolicy,
    SourceDefinition,
    SourceRegistry,
    VersionPolicy,
    load_source_registry,
)

__all__ = [
    "AccessClass",
    "AnnotationLayer",
    "AnnotationProposal",
    "ArtifactStorePort",
    "ConceptLink",
    "CoverageCell",
    "CoveragePlannerPort",
    "CoverageReport",
    "DatasetSnapshot",
    "DeduplicatorPort",
    "DiscoveredArtifact",
    "DocumentParserPort",
    "DuckDBMiningCatalog",
    "FsspecArtifactStore",
    "LocalArtifactStore",
    "LicenseMode",
    "MinedDocument",
    "MiningQualityGate",
    "ParquetSnapshotWriter",
    "ProposalLabelerPort",
    "PolicyDecision",
    "QualityGatePort",
    "RedistributionPolicy",
    "RetentionPolicy",
    "RelationProposal",
    "ReviewBackendPort",
    "ReviewStatus",
    "SourceArtifact",
    "SourceConnectorPort",
    "SourceDefinition",
    "SourcePolicyGate",
    "SourceRegistry",
    "SourceRequest",
    "StoredObject",
    "VersionPolicy",
    "load_source_registry",
]
