"""Reusable acquisition, curation, and dataset-snapshot primitives."""

from clingrounder.mining.annotation_manifest import (
    AnnotationManifestResult,
    materialize_annotation_manifest,
)
from clingrounder.mining.abbreviations import (
    AbbreviationMiningPolicy,
    AbbreviationMiningResult,
    benchmark_abbreviation_knowledge,
    build_runtime_abbreviation_table,
    load_abbreviation_mining_policy,
    load_snapshot_splits,
    mine_abbreviations,
)
from clingrounder.mining.catalog import DuckDBMiningCatalog, ParquetSnapshotWriter
from clingrounder.mining.connectors import connector_from_definition
from clingrounder.mining.cooccurrence import (
    CooccurrenceMiningPolicy,
    CooccurrenceMiningResult,
    load_cooccurrence_policy,
    mine_cooccurrence_relations,
)
from clingrounder.mining.coverage import CoverageCubePlanner, CoverageTarget, ReviewPriority
from clingrounder.mining.curation import (
    AnnotationCurationPolicy,
    AnnotationCurationResult,
    curate_annotations,
    load_annotation_curation_policy,
)
from clingrounder.mining.crosswalk import (
    MentionCrosswalkPolicy,
    MentionCrosswalkRecord,
    MentionCrosswalkResult,
    crosswalk_mentions,
    load_crosswalk_policies,
)
from clingrounder.mining.crosswalk_links import (
    CrosswalkLinkMaterializationPolicy,
    CrosswalkLinkMaterializationResult,
    load_crosswalk_link_policy,
    load_crosswalk_rows,
    materialize_exact_crosswalk_links,
)
from clingrounder.mining.dedup import (
    DuplicateGroup,
    DuplicateGroupKind,
    StableTextDeduplicator,
)
from clingrounder.mining.labeling import (
    BatchedProposalLabelerAdapter,
    ConsensusProposalLabeler,
    PolicyAwareProposalLabelerAdapter,
)
from clingrounder.mining.graph_knowledge import (
    GraphCompilationConfig,
    compile_knowledge_graph,
)
from clingrounder.mining.harmonization import (
    AnnotationHarmonizationPolicy,
    AnnotationHarmonizationResult,
    AnnotationHarmonizationRule,
    harmonize_annotations,
    load_annotation_harmonization_policy,
)
from clingrounder.mining.fusion import (
    CorpusFusionPlan,
    CorpusFusionResult,
    CorpusPartition,
    FusionRunResult,
    FusionSourcePlan,
    RejectedRelation,
    fuse_corpora,
    load_corpus_fusion_plan,
    run_corpus_fusion_plan,
)
from clingrounder.mining.knowledge import (
    AliasKnowledgeCompilationResult,
    MinedAliasPromotionPolicy,
    compile_mined_aliases,
    load_alias_promotion_policy,
)
from clingrounder.mining.lexicon import (
    MentionInventoryEntry,
    MentionInventoryResult,
    build_mention_inventory,
    load_mention_inventory,
)
from clingrounder.mining.linked_aliases import (
    LinkedAliasProposalPolicy,
    LinkedAliasProposalResult,
    build_linked_alias_proposals,
    load_linked_alias_policy,
)
from clingrounder.mining.model_dataset import (
    SpanDatasetConfig,
    export_span_dataset,
    iter_span_training_records,
    load_dataset_splits,
)
from clingrounder.mining.parsers import parser_from_definition
from clingrounder.mining.ports import (
    ArtifactStorePort,
    CoveragePlannerPort,
    DeduplicatorPort,
    DocumentParserPort,
    ProposalLabelerPort,
    QualityGatePort,
    RelationLabelerPort,
    ReviewBackendPort,
    SourceConnectorPort,
)
from clingrounder.mining.policy import MiningQualityGate, PolicyDecision, SourcePolicyGate
from clingrounder.mining.profile import build_dataset_profile, profile_blocking_issue_count
from clingrounder.mining.records import (
    AccessClass,
    AnnotationLayer,
    AnnotationProposal,
    ConceptLink,
    CoverageCell,
    CoverageReport,
    DatasetSnapshot,
    DiscoveredArtifact,
    MinedDocument,
    RedistributionPolicy,
    RelationProposal,
    ReviewStatus,
    SourceArtifact,
    SourceRequest,
    StoredObject,
    content_addressed_object_uri,
)
from clingrounder.mining.reconciliation import (
    DocumentCanonicalMapping,
    DuplicateReconciliationReport,
    ExactDuplicateReconciliationResult,
    reconcile_exact_duplicates,
)
from clingrounder.mining.release import (
    LoadedMiningReleaseSpec,
    MiningReleaseLock,
    MiningReleaseSpec,
    ReleaseArtifactSpec,
    ReleaseCasObjectSpec,
    ReleaseRebuildStep,
    build_mining_release_lock,
    load_mining_release_spec,
    verify_mining_release_lock,
)
from clingrounder.mining.recognition_benchmark import (
    benchmark_recognition_dictionary,
)
from clingrounder.mining.recognition_knowledge import (
    RecognitionKnowledgeCompilationResult,
    RecognitionKnowledgePolicy,
    compile_recognition_knowledge,
    load_recognition_knowledge_policy,
)
from clingrounder.mining.storage import (
    FsspecArtifactStore,
    LocalArtifactStore,
    materialize_stored_object,
)
from clingrounder.mining.registry import (
    LicenseMode,
    RetentionPolicy,
    SourceDefinition,
    SourceRegistry,
    VersionPolicy,
    load_source_registry,
)
from clingrounder.mining.source_status import (
    PromotionBoundary,
    SourceProcessingIndex,
    SourceProcessingRecord,
    SourceProcessingState,
    load_source_processing_index,
    validate_source_processing_paths,
)
from clingrounder.mining.review import JsonlReviewBackend
from clingrounder.mining.quality import (
    AgreementThresholds,
    GoldAgreementGate,
    ReviewAgreementEvaluator,
    ReviewAgreementReport,
)
from clingrounder.mining.runner import (
    MiningPlan,
    MiningPlanResult,
    SourceJob,
    load_mining_plan,
    run_mining_plan,
)
from clingrounder.mining.snapshot import SnapshotBuilder, SnapshotSplitConfig
from clingrounder.mining.synthetic import (
    MinimalPairGenerator,
    RenderedScenario,
    ScenarioEntity,
    ScenarioGraph,
    ScenarioRelation,
    SentinelScenarioRenderer,
)

__all__ = [
    "AccessClass",
    "AbbreviationMiningPolicy",
    "AbbreviationMiningResult",
    "AgreementThresholds",
    "AnnotationLayer",
    "AnnotationManifestResult",
    "AnnotationHarmonizationPolicy",
    "AnnotationHarmonizationResult",
    "AnnotationHarmonizationRule",
    "AnnotationProposal",
    "AnnotationCurationPolicy",
    "AnnotationCurationResult",
    "ArtifactStorePort",
    "AliasKnowledgeCompilationResult",
    "BatchedProposalLabelerAdapter",
    "ConceptLink",
    "CooccurrenceMiningPolicy",
    "CooccurrenceMiningResult",
    "CorpusFusionPlan",
    "CorpusFusionResult",
    "CorpusPartition",
    "CrosswalkLinkMaterializationPolicy",
    "CrosswalkLinkMaterializationResult",
    "CoverageCell",
    "CoverageCubePlanner",
    "CoveragePlannerPort",
    "CoverageReport",
    "CoverageTarget",
    "DatasetSnapshot",
    "DeduplicatorPort",
    "DiscoveredArtifact",
    "GraphCompilationConfig",
    "DocumentParserPort",
    "DocumentCanonicalMapping",
    "DuckDBMiningCatalog",
    "DuplicateGroup",
    "DuplicateGroupKind",
    "DuplicateReconciliationReport",
    "ExactDuplicateReconciliationResult",
    "FsspecArtifactStore",
    "FusionRunResult",
    "FusionSourcePlan",
    "GoldAgreementGate",
    "LocalArtifactStore",
    "LicenseMode",
    "LinkedAliasProposalPolicy",
    "LinkedAliasProposalResult",
    "LoadedMiningReleaseSpec",
    "MinedDocument",
    "PromotionBoundary",
    "MinimalPairGenerator",
    "MiningQualityGate",
    "MinedAliasPromotionPolicy",
    "MiningPlan",
    "MiningPlanResult",
    "MiningReleaseLock",
    "MiningReleaseSpec",
    "MentionInventoryEntry",
    "MentionInventoryResult",
    "MentionCrosswalkPolicy",
    "MentionCrosswalkRecord",
    "MentionCrosswalkResult",
    "ParquetSnapshotWriter",
    "ProposalLabelerPort",
    "PolicyDecision",
    "PolicyAwareProposalLabelerAdapter",
    "QualityGatePort",
    "RedistributionPolicy",
    "RejectedRelation",
    "RecognitionKnowledgeCompilationResult",
    "RecognitionKnowledgePolicy",
    "RelationLabelerPort",
    "RetentionPolicy",
    "RelationProposal",
    "RenderedScenario",
    "ReviewPriority",
    "ReviewAgreementEvaluator",
    "ReviewAgreementReport",
    "ReviewBackendPort",
    "ReviewStatus",
    "ReleaseArtifactSpec",
    "ReleaseCasObjectSpec",
    "ReleaseRebuildStep",
    "SourceArtifact",
    "SourceJob",
    "SourceConnectorPort",
    "SourceDefinition",
    "SourceProcessingIndex",
    "SourceProcessingRecord",
    "SourceProcessingState",
    "SourcePolicyGate",
    "SourceRegistry",
    "SourceRequest",
    "ScenarioEntity",
    "ScenarioGraph",
    "ScenarioRelation",
    "SentinelScenarioRenderer",
    "StableTextDeduplicator",
    "SnapshotBuilder",
    "SnapshotSplitConfig",
    "StoredObject",
    "SpanDatasetConfig",
    "VersionPolicy",
    "build_dataset_profile",
    "benchmark_abbreviation_knowledge",
    "build_runtime_abbreviation_table",
    "build_mining_release_lock",
    "build_linked_alias_proposals",
    "compile_knowledge_graph",
    "content_addressed_object_uri",
    "benchmark_recognition_dictionary",
    "build_mention_inventory",
    "crosswalk_mentions",
    "compile_mined_aliases",
    "compile_recognition_knowledge",
    "curate_annotations",
    "connector_from_definition",
    "ConsensusProposalLabeler",
    "JsonlReviewBackend",
    "load_source_registry",
    "materialize_stored_object",
    "materialize_annotation_manifest",
    "load_source_processing_index",
    "load_crosswalk_policies",
    "load_crosswalk_link_policy",
    "load_crosswalk_rows",
    "load_annotation_curation_policy",
    "load_mention_inventory",
    "load_mining_plan",
    "load_mining_release_spec",
    "load_linked_alias_policy",
    "load_cooccurrence_policy",
    "export_span_dataset",
    "fuse_corpora",
    "harmonize_annotations",
    "iter_span_training_records",
    "load_dataset_splits",
    "load_corpus_fusion_plan",
    "load_annotation_harmonization_policy",
    "load_recognition_knowledge_policy",
    "load_alias_promotion_policy",
    "load_abbreviation_mining_policy",
    "mine_cooccurrence_relations",
    "mine_abbreviations",
    "materialize_exact_crosswalk_links",
    "parser_from_definition",
    "profile_blocking_issue_count",
    "reconcile_exact_duplicates",
    "run_corpus_fusion_plan",
    "run_mining_plan",
    "load_snapshot_splits",
    "validate_source_processing_paths",
    "verify_mining_release_lock",
]
